terraform {
  required_version = ">= 1.3"

  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 4.0"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "${var.prefix}-rg"
  location = var.location
}

module "cosmosdb" {
  source = "../.."

  name                = "${var.prefix}-mongo"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location

  # Every database gets its own user which owns that database only. Passwords
  # are generated by the module and end up in the state, so keep the state
  # encrypted or read them out into a secret store.
  databases = [
    {
      name       = "orders"
      throughput = 400
    },
    {
      name           = "invoices"
      max_throughput = 1000
    },
    {
      # A user name that differs from the database name.
      name     = "reporting"
      username = "reporting-app"
    },
  ]

  tags = {
    example = "password-authentication"
  }
}
